#!/usr/bin/with-contenv sh

if [ -n "$MJPEG_STREAMER_INPUT" ]; then
  echo "Deprecation warning: the environment variable '\$MJPEG_STREAMER_INPUT' was renamed to '\$MJPG_STREAMER_INPUT'"

  MJPG_STREAMER_INPUT=$MJPEG_STREAMER_INPUT
fi

function start_mjpg_streamer {
  if ! expr "$1" : ".*\.so.*" > /dev/null; then
    INPUT="input_uvc.so $1"
  else
    INPUT="$1"
  fi

  echo mjpg_streamer \
  -i "/usr/local/lib/mjpg-streamer/$INPUT" -d "$2" \
  -o "/usr/local/lib/mjpg-streamer/output_http.so" -w "/usr/local/share/mjpg-streamer/www" -p "$3" 
}



if [ -n "$MJPG_STREAMER_INPUT_3" ] ; then  
    $(start_mjpg_streamer "$MJPG_STREAMER_INPUT_3" "$CAMERA_DEV_3" 8082) &
fi

if [ -n "$MJPG_STREAMER_INPUT_2" ] ; then  
    $(start_mjpg_streamer "$MJPG_STREAMER_INPUT_2" "$CAMERA_DEV_2" 8081) &
fi

# alias for single camera setup
if [ -n "$CAMERA_DEV" ]; then
    CAMERA_DEV_1="$CAMERA_DEV"
    MJPG_STREAMER_INPUT_1="$MJPG_STREAMER_INPUT"
fi

exec $(start_mjpg_streamer "$MJPG_STREAMER_INPUT_1" "$CAMERA_DEV_1" 8080)